name: esacci-esgf
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.1.18=0
  - certifi=2017.1.23=py34_0
  - ncurses=5.9=10
  - openssl=1.0.2o=0
  - pip=9.0.1=py34_0
  - python=3.4.5=2
  - readline=6.2=0
  - setuptools=32.3.1=py34_0
  - sqlite=3.13.0=1
  - tk=8.5.19=2
  - wheel=0.29.0=py34_0
  - xz=5.2.3=0
  - zlib=1.2.11=0
  - pip:
    - asn1crypto==0.24.0
    - astroid==1.6.3
    - attrs==17.4.0
    - cached-property==1.3.0
    - cffi==1.11.5
    - chardet==3.0.4
    - cryptography==2.2.2
    - idna==2.6
    - isort==4.3.4
    - lazy-object-proxy==1.3.1
    - mccabe==0.6.1
    - netcdf4==1.3.1
    - numpy==1.14.2
    - pluggy==0.6.0
    - psycopg2-binary==2.7.4
    - py==1.5.3
    - pycodestyle==2.4.0
    - pycparser==2.18
    - pylint==1.8.4
    - pysolr==3.7.0
    - pytest==3.3.2
    - requests==2.18.4
    - six==1.11.0
    - urllib3==1.22
    - wrapt==1.10.11
    - git+https://github.com/cedadev/tds-utils
